token: "lip_perwEsAEdICxEhVSZ5HK"    # Lichess OAuth2 Token.
url: "https://lichess.org/"  # Lichess base URL.

engine:                      # Engine settings.
  dir: "./"                  # Directory containing engines, relative to this project.
  name: "chess-engine"    # Binary name of the engine to use.
  protocol: "uci"            # "uci" or "xboard"
  ponder: true               # Think on opponent's time.
  polyglot:
    enabled: true           # Activate polyglot book.
    book:
      standard:              # List of book file paths for variant standard.
        - Goi5.1.bin
        - Drawkiller_EloZoom_big.bin
        - Goi5.1.bin
        - Perfect2021.bin
        - tcec.bin
        - komodo.bin
        - elo3300.bin
        - Cerebellum3Merge.bin
#      atomic: # list of book file paths for variant atomic
#      etc.
#      use the same pattern for giveaway, crazyhouse, horde, kingofthehill, racingkings, 3check as well
      min_weight: 100          # selects move with highest weight but not below this value
      selection: "best_move" # move slection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in 2. and 3. case)
    max_depth: 245             # half move max depth
# engine_options:           # any custom command line params to pass to the engine
#   cpuct: 3.1
  uci_options:               # arbitrary UCI options passed to the engine
 
option name Contempt type spin : 24
option name Analysis Contempt type combo : Both var Off var White var Black var Both
option name Threads type spin : 20
option name Hash type spin : 32768
option name Ponder type check : true
option name MultiPV type spin : 1
option name Skill Level type spin : 20
option name Move Overhead type spin : 5000
option name nodestime type spin : 0
option name UCI_Chess960 type check : false
option name UCI_AnalyseMode type check : false
option name UCI_LimitStrength type check : false
option name UCI_Elo type spin : 2850
option name UCI_ShowWDL type check : false
option name SyzygyPath type string : <empty>
option name SyzygyProbeDepth type spin : 100
option name Syzygy50MoveRule type check : true
option name SyzygyProbeLimit type spin : 7
option name Use NNUE type check : true
#    go_commands:             # additional options to pass to the UCI go command
#      nodes: 5000               # Search so many nodes only.
#      depth: 20               # Search depth ply only.
#      movetime: 1         # Integer. Search exactly movetime milliseconds.
#  xboard_options:            # arbitrary xboard options passed to the engine
#    cores: "4"
#    memory: "4096"
#    egtpath:                 # dir containing egtb, relative to this project
#     gaviota: "Gaviota path"
#     nalimov: "Nalimov Path"
#     scorpio: "Scorpio Path"
#     syzygy: "Syzygy Path"
#  silence_stderr: false      # some engines (yes you, leela) are very noisy

abort_time: 30               # time to abort a game in seconds when there is no activity
fake_think_time: false       # artificially slow down the bot to pretend like it's thinking

challenge:                   # incoming challenges
  concurrency: 1             # number of games to play simultaneously
  sort_by: "best"            # possible values: "best", "first"
  accept_bot: true          # accepts challenges coming from other bots
  only_bot: false            # accept challenges by bots only
  max_increment: 180         # maximum amount of increment to accaept a challenge. the max is 180. set to 0 for no increment
  min_increment: 0           # minimum amount of increment to accept a challenge
  variants:                  # chess variants to accept (http://lichess.org/variant)
    - standard
#   - fromPosition
#   - antichess
#   - atomic
    - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:             # time controls to accept
    - bullet
    - blitz
    - rapid
#   - classical
#   - correspondence
  modes:                     # game modes to accept
    - casual                 # unrated games
    - rated                  # rated games - must comment if the engine doesn't try to win
